import sqlite3, os
from datetime import datetime
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash

DATABASE_URL=os.environ.get("DATABASE_URL", "").strip()
USE_POSTGRES=bool(DATABASE_URL)
if USE_POSTGRES:
    import psycopg
    from psycopg.rows import dict_row

BASE=os.path.dirname(os.path.abspath(__file__))
DB=os.path.join(BASE,"filetrack.db")
UPLOADS=os.path.join(BASE,"uploads")
os.makedirs(UPLOADS,exist_ok=True)

app=Flask(__name__)
app.secret_key=os.environ.get("FILETRACK_SECRET","change-this-secret-key")

LGAS=["Katsina A","Katsina B","Batagarawa","Kaita","Jibia","Rimi","Charanchi"]
BRANCHES=["CIM","CW&HS","CDS"]
PRIORITIES=["Normal","High","Urgent"]
ROLES=["Administrator","Zonal Inspector","LGI Officer","Branch Official","Supporting Staff"]

class HybridRow(dict):
    def __getitem__(self,key):
        if isinstance(key,int):
            return list(self.values())[key]
        return super().__getitem__(key)

def hybrid_row(cursor):
    cols=[d.name for d in cursor.description]
    return HybridRow(zip(cols, cursor.fetchone()))

def pg_row(cursor):
    values=cursor.fetchone()
    if values is None: return None
    cols=[d.name for d in cursor.description]
    return HybridRow(zip(cols, values))

class PGConnection:
    def __init__(self,url):
        self.conn=psycopg.connect(url)
    def execute(self,sql,params=()):
        # Convert the existing SQLite-style placeholders to PostgreSQL placeholders.
        return self.conn.execute(sql.replace("?","%s"), params)
    def commit(self): return self.conn.commit()
    def close(self): return self.conn.close()

def db():
    if USE_POSTGRES:
        class Conn:
            def __init__(self,url): self.conn=psycopg.connect(url, row_factory=pg_row)
            def execute(self,sql,params=()): return self.conn.execute(sql.replace("?","%s"), params)
            def commit(self): return self.conn.commit()
            def close(self): return self.conn.close()
        return Conn(DATABASE_URL)
    c=sqlite3.connect(DB)
    c.row_factory=sqlite3.Row
    return c

def now():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def init_db():
    c=db()
    if USE_POSTGRES:
        statements=[
        """CREATE TABLE IF NOT EXISTS files(
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, file_id TEXT UNIQUE NOT NULL, title TEXT NOT NULL,
          reference_no TEXT, lga TEXT NOT NULL, lgi_name TEXT, received_by TEXT NOT NULL, received_at TEXT NOT NULL,
          priority TEXT DEFAULT 'Normal', description TEXT, attachment TEXT, status TEXT DEFAULT 'Received',
          current_location TEXT DEFAULT 'Katsina Zonal Office', created_at TEXT NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS movements(
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, file_id TEXT NOT NULL, from_location TEXT NOT NULL,
          to_location TEXT NOT NULL, forwarded_by TEXT, receiving_officer TEXT, action TEXT, forwarded_at TEXT NOT NULL,
          acknowledged_at TEXT, status TEXT DEFAULT 'Forwarded', remarks TEXT, submitted_by TEXT, submitted_at TEXT)""",
        """CREATE TABLE IF NOT EXISTS audit_logs(
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, file_id TEXT NOT NULL, action TEXT NOT NULL,
          official TEXT, details TEXT, created_at TEXT NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS users(
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, full_name TEXT NOT NULL, username TEXT UNIQUE NOT NULL,
          password_hash TEXT NOT NULL, role TEXT NOT NULL, office TEXT, lga TEXT, active INTEGER DEFAULT 1, created_at TEXT NOT NULL)""",
        """CREATE TABLE IF NOT EXISTS inspections(
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, inspection_id TEXT UNIQUE NOT NULL, lga TEXT NOT NULL,
          ppa_employer TEXT, corps_member TEXT, subject TEXT NOT NULL, findings TEXT NOT NULL, recommendations TEXT,
          inspected_by TEXT NOT NULL, inspected_at TEXT NOT NULL, status TEXT DEFAULT 'Submitted to ZI')""",
        """CREATE TABLE IF NOT EXISTS reports(
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id TEXT UNIQUE NOT NULL, lga TEXT NOT NULL,
          report_type TEXT NOT NULL, ppa_employer TEXT, corps_member TEXT, subject TEXT NOT NULL, report_body TEXT NOT NULL,
          issued_by TEXT NOT NULL, issued_at TEXT NOT NULL, status TEXT DEFAULT 'Issued')"""
        ]
        for statement in statements: c.execute(statement)
        c.execute("ALTER TABLE movements ADD COLUMN IF NOT EXISTS submitted_by TEXT")
        c.execute("ALTER TABLE movements ADD COLUMN IF NOT EXISTS submitted_at TEXT")
    else:
        c.executescript("""
        CREATE TABLE IF NOT EXISTS files(id INTEGER PRIMARY KEY AUTOINCREMENT,file_id TEXT UNIQUE NOT NULL,title TEXT NOT NULL,reference_no TEXT,lga TEXT NOT NULL,lgi_name TEXT,received_by TEXT NOT NULL,received_at TEXT NOT NULL,priority TEXT DEFAULT 'Normal',description TEXT,attachment TEXT,status TEXT DEFAULT 'Received',current_location TEXT DEFAULT 'Katsina Zonal Office',created_at TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS movements(id INTEGER PRIMARY KEY AUTOINCREMENT,file_id TEXT NOT NULL,from_location TEXT NOT NULL,to_location TEXT NOT NULL,forwarded_by TEXT,receiving_officer TEXT,action TEXT,forwarded_at TEXT NOT NULL,acknowledged_at TEXT,status TEXT DEFAULT 'Forwarded',remarks TEXT);
        CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,file_id TEXT NOT NULL,action TEXT NOT NULL,official TEXT,details TEXT,created_at TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,office TEXT,lga TEXT,active INTEGER DEFAULT 1,created_at TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS inspections(id INTEGER PRIMARY KEY AUTOINCREMENT,inspection_id TEXT UNIQUE NOT NULL,lga TEXT NOT NULL,ppa_employer TEXT,corps_member TEXT,subject TEXT NOT NULL,findings TEXT NOT NULL,recommendations TEXT,inspected_by TEXT NOT NULL,inspected_at TEXT NOT NULL,status TEXT DEFAULT 'Submitted to ZI');
        CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,report_id TEXT UNIQUE NOT NULL,lga TEXT NOT NULL,report_type TEXT NOT NULL,ppa_employer TEXT,corps_member TEXT,subject TEXT NOT NULL,report_body TEXT NOT NULL,issued_by TEXT NOT NULL,issued_at TEXT NOT NULL,status TEXT DEFAULT 'Issued');
        """)
        for statement in ["ALTER TABLE movements ADD COLUMN submitted_by TEXT","ALTER TABLE movements ADD COLUMN submitted_at TEXT"]:
            try: c.execute(statement)
            except sqlite3.OperationalError as e:
                if "duplicate column name" not in str(e).lower(): raise
    c.commit(); c.close()

def user_count():
    c=db()
    n=c.execute("SELECT COUNT(*) FROM users").fetchone()[0]
    c.close()
    return n

def current_user():
    uid=session.get("user_id")
    if not uid:
        return None
    c=db()
    u=c.execute("SELECT * FROM users WHERE id=? AND active=1",(uid,)).fetchone()
    c.close()
    return u

@app.context_processor
def inject_user():
    return {"current_user": current_user()}

def login_required(view):
    @wraps(view)
    def wrapped(*args,**kwargs):
        if not current_user():
            return redirect(url_for("login",next=request.path))
        return view(*args,**kwargs)
    return wrapped

def admin_required(view):
    @wraps(view)
    def wrapped(*args,**kwargs):
        u=current_user()
        if not u:
            return redirect(url_for("login",next=request.path))
        if u["role"]!="Administrator":
            flash("Administrator access is required.","error")
            return redirect(url_for("dashboard"))
        return view(*args,**kwargs)
    return wrapped

def official_name():
    u=current_user()
    return u["full_name"] if u else ""

def role_is(role):
    u=current_user()
    return bool(u and u["role"] == role)

def can_receive_register():
    # Supporting Staff are the primary registry assistants for incoming LGI files.
    # Administrator and Zonal Inspector may also register a file when necessary.
    u=current_user()
    return bool(u and u["role"] in ("Administrator", "Zonal Inspector", "Supporting Staff"))

def can_operate_file_movement():
    # Only the Administrator or Zonal Inspector controls forwarding/returning.
    # Supporting Staff register incoming files and later confirm physical delivery.
    u=current_user()
    return bool(u and u["role"] in ("Administrator", "Zonal Inspector"))

def supporting_staff_required(view):
    @wraps(view)
    def wrapped(*args,**kwargs):
        if not current_user():
            return redirect(url_for("login",next=request.path))
        if current_user()["role"] != "Supporting Staff":
            flash("This action is reserved for Supporting Staff responsible for physical file delivery.","error")
            return redirect(url_for("detail",file_id=kwargs.get("file_id","")))
        return view(*args,**kwargs)
    return wrapped


def registry_required(view):
    @wraps(view)
    def wrapped(*args,**kwargs):
        if not current_user():
            return redirect(url_for("login",next=request.path))
        if not can_receive_register():
            flash("Only the Administrator, Zonal Inspector or Supporting Staff may register incoming LGI files.","error")
            return redirect(url_for("dashboard"))
        return view(*args,**kwargs)
    return wrapped

def movement_required(view):
    @wraps(view)
    def wrapped(*args,**kwargs):
        if not current_user():
            return redirect(url_for("login",next=request.path))
        if not can_operate_file_movement():
            flash("Only the Administrator or Zonal Inspector may forward or return files. Supporting Staff register incoming files and confirm physical delivery.","error")
            return redirect(url_for("dashboard"))
        return view(*args,**kwargs)
    return wrapped

def next_file_id():
    c=db()
    n=c.execute("SELECT COUNT(*) AS n FROM files").fetchone()["n"]
    c.close()
    return f"KZO-FM-{datetime.now().year}-{n+1:04d}"

@app.route("/login",methods=["GET","POST"])
def login():
    if current_user():
        return redirect(url_for("dashboard"))
    if request.method=="POST":
        username=request.form.get("username","").strip()
        password=request.form.get("password","")
        c=db()
        u=c.execute("SELECT * FROM users WHERE username=?",(username,)).fetchone()
        c.close()
        if u and u["active"] and check_password_hash(u["password_hash"],password):
            session.clear()
            session["user_id"]=u["id"]
            session["username"]=u["username"]
            session["full_name"]=u["full_name"]
            session["role"]=u["role"]
            nxt=request.args.get("next") or request.form.get("next") or url_for("dashboard")
            return redirect(nxt)
        flash("Invalid username or password, or the account is inactive.","error")
    return render_template("login.html")

@app.route("/logout")
def logout():
    session.clear()
    flash("You have been logged out.","success")
    return redirect(url_for("login"))

@app.route("/setup",methods=["GET","POST"])
def setup():
    if user_count()>0:
        flash("Initial setup has already been completed.","error")
        return redirect(url_for("login"))
    if request.method=="POST":
        full_name=request.form.get("full_name","").strip()
        username=request.form.get("username","").strip()
        password=request.form.get("password","")
        confirm=request.form.get("confirm_password","")
        if not full_name or not username or not password:
            flash("All required fields must be completed.","error")
        elif len(password)<8:
            flash("Password must be at least 8 characters.","error")
        elif password!=confirm:
            flash("Passwords do not match.","error")
        else:
            c=db()
            c.execute("""INSERT INTO users
                (full_name,username,password_hash,role,office,lga,active,created_at)
                VALUES(?,?,?,?,?,?,1,?)""",
                (full_name,username,generate_password_hash(password),
                 "Administrator","Katsina Zonal Office","",now()))
            c.commit()
            c.close()
            flash("Administrator account created. Please log in.","success")
            return redirect(url_for("login"))
    return render_template("setup.html")

@app.route("/users",methods=["GET","POST"])
@admin_required
def users():
    if request.method=="POST":
        full_name=request.form.get("full_name","").strip()
        username=request.form.get("username","").strip()
        password=request.form.get("password","")
        role=request.form.get("role","").strip()
        office=request.form.get("office","").strip()
        lga=request.form.get("lga","").strip()
        if not full_name or not username or not password or role not in ROLES:
            flash("Full name, username, password and valid role are required.","error")
        elif len(password)<8:
            flash("Password must be at least 8 characters.","error")
        else:
            c=db()
            try:
                c.execute("""INSERT INTO users
                    (full_name,username,password_hash,role,office,lga,active,created_at)
                    VALUES(?,?,?,?,?,?,1,?)""",
                    (full_name,username,generate_password_hash(password),
                     role,office,lga,now()))
                c.commit()
                flash(f"{full_name} account created successfully.","success")
            except sqlite3.IntegrityError:
                flash("That username already exists.","error")
            finally:
                c.close()
        return redirect(url_for("users"))
    c=db()
    rows=c.execute("SELECT * FROM users ORDER BY full_name").fetchall()
    c.close()
    return render_template("users.html",users=rows,roles=ROLES,lgas=LGAS)

@app.route("/users/<int:user_id>/toggle",methods=["POST"])
@admin_required
def toggle_user(user_id):
    if user_id==current_user()["id"]:
        flash("You cannot deactivate your own account.","error")
        return redirect(url_for("users"))
    c=db()
    c.execute("UPDATE users SET active=CASE WHEN active=1 THEN 0 ELSE 1 END WHERE id=?",(user_id,))
    c.commit()
    c.close()
    flash("Account status updated.","success")
    return redirect(url_for("users"))

@app.route("/")
@login_required
def dashboard():
    u=current_user()
    role=u["role"]
    c=db()

    # Administrator / Zonal Inspector: full zonal operational picture.
    if role in ("Administrator", "Zonal Inspector"):
        total=c.execute("SELECT COUNT(*) FROM files").fetchone()[0]
        received=c.execute("SELECT COUNT(*) FROM files WHERE status='Received'").fetchone()[0]
        forwarded=c.execute("SELECT COUNT(*) FROM files WHERE status='Forwarded'").fetchone()[0]
        submitted=c.execute("SELECT COUNT(*) FROM files WHERE status='Submitted'").fetchone()[0]
        returned=c.execute("SELECT COUNT(*) FROM files WHERE status='Returned'").fetchone()[0]
        stats={"Total":total,"Received":received,"Forwarded":forwarded,
               "Submitted":submitted,"Returned":returned}
        branch_counts={}
        for branch in BRANCHES:
            branch_counts[branch]=c.execute(
                "SELECT COUNT(*) FROM files WHERE current_location=?",(branch,)).fetchone()[0]
        branches=[(branch,branch_counts[branch]) for branch in BRANCHES]
        recent=c.execute("SELECT * FROM files ORDER BY id DESC LIMIT 8").fetchall()

    # Supporting Staff: show registry work and the physical-delivery queue,
    # rather than the complete management dashboard.
    elif role == "Supporting Staff":
        name=u["full_name"]
        surname=name.strip().split()[-1] if name.strip() else ""
        registered=c.execute(
            "SELECT COUNT(*) FROM files WHERE lower(received_by)=lower(?) OR lower(received_by)=lower(?) OR lower(received_by) LIKE ?",
            (name, u["username"], f"%{surname.lower()}%")
        ).fetchone()[0]
        review=c.execute(
            "SELECT COUNT(*) FROM files WHERE status='Received' AND (lower(received_by)=lower(?) OR lower(received_by)=lower(?) OR lower(received_by) LIKE ?)",
            (name, u["username"], f"%{surname.lower()}%")
        ).fetchone()[0]
        delivery=c.execute("SELECT COUNT(*) FROM files WHERE status='Forwarded'").fetchone()[0]
        my_submitted=c.execute("SELECT COUNT(*) FROM movements WHERE submitted_by=?",(name,)).fetchone()[0]
        stats={"registered":registered,"review":review,"delivery":delivery,"my_submitted":my_submitted}
        branches=[]
        recent=c.execute(
            "SELECT * FROM files WHERE lower(received_by)=lower(?) OR lower(received_by)=lower(?) OR lower(received_by) LIKE ? ORDER BY id DESC LIMIT 8",
            (name, u["username"], f"%{surname.lower()}%")
        ).fetchall()

    # LGI Officer: only the officer's assigned LGA is relevant.
    elif role == "LGI Officer":
        lga=(u["lga"] or "").strip()
        total=c.execute("SELECT COUNT(*) FROM files WHERE lga=?",(lga,)).fetchone()[0]
        received=c.execute("SELECT COUNT(*) FROM files WHERE lga=? AND status='Received'",(lga,)).fetchone()[0]
        forwarded=c.execute("SELECT COUNT(*) FROM files WHERE lga=? AND status='Forwarded'",(lga,)).fetchone()[0]
        submitted=c.execute("SELECT COUNT(*) FROM files WHERE lga=? AND status='Submitted'",(lga,)).fetchone()[0]
        stats={"total":total,"received":received,"forwarded":forwarded,"submitted":submitted}
        branches=[]
        recent=c.execute("SELECT * FROM files WHERE lga=? ORDER BY id DESC LIMIT 8",(lga,)).fetchall()

    # Branch Official: office should contain CIM, CW&HS or CDS.
    else:
        branch=(u["office"] or "").strip()
        incoming=c.execute("SELECT COUNT(*) FROM files WHERE current_location=?",(branch,)).fetchone()[0]
        pending=c.execute("SELECT COUNT(*) FROM files WHERE current_location=? AND status='Forwarded'",(branch,)).fetchone()[0]
        submitted=c.execute("SELECT COUNT(*) FROM files WHERE current_location=? AND status='Submitted'",(branch,)).fetchone()[0]
        returned=c.execute("SELECT COUNT(*) FROM files WHERE current_location=? AND status='Returned'",(branch,)).fetchone()[0]
        stats={"incoming":incoming,"pending":pending,"submitted":submitted,"returned":returned}
        branches=[]
        recent=c.execute("SELECT * FROM files WHERE current_location=? ORDER BY id DESC LIMIT 8",(branch,)).fetchall()

    c.close()
    return render_template("dashboard.html",stats=stats,branches=branches,recent=recent)

@app.route("/files")
@login_required
def files_page():
    q=request.args.get("q","").strip()
    status=request.args.get("status","").strip()
    branch=request.args.get("branch","").strip()
    c=db()
    sql="SELECT * FROM files WHERE 1=1"; args=[]
    if q:
        sql += """ AND (file_id LIKE ? OR title LIKE ? OR reference_no LIKE ?
                    OR lga LIKE ? OR lgi_name LIKE ? OR current_location LIKE ?)"""
        args += [f"%{q}%"]*6
    if status:
        sql+=" AND status=?"; args.append(status)
    if branch:
        sql+=" AND current_location=?"; args.append(branch)
    sql+=" ORDER BY id DESC"
    rows=c.execute(sql,args).fetchall()
    c.close()
    return render_template("files.html",rows=rows,q=q,status=status,
                           branch=branch,branches=BRANCHES)

@app.route("/receive",methods=["GET","POST"])
@registry_required
def receive():
    if request.method=="POST":
        title=request.form.get("title","").strip()
        if not title:
            flash("File/document title is required.","error")
            return redirect(url_for("receive"))
        t=now(); fid=next_file_id(); attachment=None
        uploaded=request.files.get("attachment")
        if uploaded and uploaded.filename:
            attachment=f"{fid}_{os.path.basename(uploaded.filename)}"
            uploaded.save(os.path.join(UPLOADS,attachment))
        official=official_name()
        c=db()
        c.execute("""INSERT INTO files
        (file_id,title,reference_no,lga,lgi_name,received_by,received_at,priority,
         description,attachment,status,current_location,created_at)
        VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)""",
        (fid,title,request.form.get("reference_no"),request.form["lga"],
         request.form.get("lgi_name"),official,t,request.form.get("priority","Normal"),
         request.form.get("description"),attachment,"Received",
         "Katsina Zonal Office",t))
        c.execute("""INSERT INTO audit_logs
        (file_id,action,official,details,created_at) VALUES(?,?,?,?,?)""",
        (fid,"FILE RECEIVED",official,"Received from "+request.form["lga"],t))
        c.commit(); c.close()
        flash(fid+" registered successfully.","success")
        return redirect(url_for("detail",file_id=fid))
    return render_template("receive.html",lgas=LGAS,priorities=PRIORITIES)

@app.route("/file/<file_id>")
@login_required
def detail(file_id):
    c=db()
    f=c.execute("SELECT * FROM files WHERE file_id=?",(file_id,)).fetchone()
    if not f:
        c.close(); return "File not found",404
    movements=c.execute("SELECT * FROM movements WHERE file_id=? ORDER BY id DESC",(file_id,)).fetchall()
    audit=c.execute("SELECT * FROM audit_logs WHERE file_id=? ORDER BY id DESC",(file_id,)).fetchall()
    c.close()
    return render_template("detail.html",f=f,movements=movements,audit=audit,branches=BRANCHES)

@app.route("/forward/<file_id>",methods=["POST"])
@movement_required
def forward(file_id):
    t=now(); c=db()
    f=c.execute("SELECT * FROM files WHERE file_id=?",(file_id,)).fetchone()
    if not f:
        c.close(); return "File not found",404
    official=official_name(); to=request.form["to_location"]
    c.execute("""INSERT INTO movements
    (file_id,from_location,to_location,forwarded_by,receiving_officer,
     action,forwarded_at,status,remarks) VALUES(?,?,?,?,?,?,?,?,?)""",
    (file_id,f["current_location"],to,official,request.form.get("receiving_officer"),
     request.form.get("action"),t,"Forwarded",request.form.get("remarks")))
    c.execute("UPDATE files SET current_location=?,status='Forwarded' WHERE file_id=?",(to,file_id))
    c.execute("""INSERT INTO audit_logs
    (file_id,action,official,details,created_at) VALUES(?,?,?,?,?)""",
    (file_id,"FILE FORWARDED",official,f"{f['current_location']} → {to}",t))
    c.commit(); c.close()
    flash(f"{file_id} forwarded to {to}.","success")
    return redirect(url_for("detail",file_id=file_id))

@app.route("/ack/<file_id>",methods=["POST"])
@supporting_staff_required
def acknowledge(file_id):
    # This is a physical-delivery confirmation by the Supporting Staff member.
    # It confirms to the Administrator/Zonal Inspector that the file was physically
    # submitted to the selected Secretariat branch; it is not a branch receipt.
    t=now(); official=official_name(); c=db()
    m=c.execute("""SELECT * FROM movements WHERE file_id=? AND status='Forwarded'
                   ORDER BY id DESC LIMIT 1""",(file_id,)).fetchone()
    if not m:
        c.close(); flash("No pending forwarded file is awaiting physical-submission confirmation.","error")
        return redirect(url_for("detail",file_id=file_id))
    c.execute("""UPDATE movements SET status='Submitted', submitted_at=?, submitted_by=?,
                 acknowledged_at=? WHERE id=?""",
              (t,official,t,m["id"]))
    c.execute("UPDATE files SET status='Submitted' WHERE file_id=?",(file_id,))
    c.execute("""INSERT INTO audit_logs
    (file_id,action,official,details,created_at) VALUES(?,?,?,?,?)""",
    (file_id,"PHYSICAL FILE SUBMITTED",official,
     f"Physical file submitted to {m['to_location']}",t))
    c.commit(); c.close()
    flash(f"Physical submission of {file_id} to {m['to_location']} confirmed.","success")
    return redirect(url_for("detail",file_id=file_id))

@app.route("/return/<file_id>",methods=["POST"])
@movement_required
def return_file(file_id):
    t=now(); official=official_name(); c=db()
    f=c.execute("SELECT * FROM files WHERE file_id=?",(file_id,)).fetchone()
    if not f:
        c.close(); return "File not found",404
    c.execute("""UPDATE files SET current_location='Katsina Zonal Office',
                 status='Returned' WHERE file_id=?""",(file_id,))
    c.execute("""INSERT INTO movements
    (file_id,from_location,to_location,forwarded_by,action,forwarded_at,status,remarks)
    VALUES(?,?,?,?,?,?,?,?)""",
    (file_id,f["current_location"],"Katsina Zonal Office",official,
     "Returned",t,"Returned",request.form.get("remarks")))
    c.execute("""INSERT INTO audit_logs
    (file_id,action,official,details,created_at) VALUES(?,?,?,?,?)""",
    (file_id,"FILE RETURNED",official,
     request.form.get("remarks") or "Returned to Zonal Office",t))
    c.commit(); c.close()
    flash("File returned to Zonal Office.","success")
    return redirect(url_for("detail",file_id=file_id))

@app.route("/download/<name>")
@login_required
def download(name):
    return send_from_directory(UPLOADS,name,as_attachment=True)

@app.get("/health")
def health():
    try:
        c=db(); c.execute("SELECT 1"); c.close()
        return {"status":"ok","database":"postgresql" if USE_POSTGRES else "sqlite"}
    except Exception as e:
        return {"status":"error","error":str(e)},500

init_db()

if __name__=="__main__":
    app.run(debug=True)
